### ISSUE TITLE
Upload SMI conformance results to http://layer5.io/landscape

### ISSUE THREAD

**Issue by s1ntaxe770r** [layer5io/meshery-smi-conformance-action#26]
#### Current Behavior

Currently SMI conformance tests results are not being uploaded to http://layer5.io/landscape 
#### Desired Behavior

Have the be uploaded after each successful run 
#### Implementation

Undefined 
#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by s1ntaxe770r** [comment]
@DelusionalOptimist  thoughts on implementation?

**Comment by DelusionalOptimist** [comment]
@s1ntaxe770r thoughts:
1. Obtaining SMI conformance results of the latest run form respective provider's database (using the `/api/smi/results` endpoint)
2. Obtaining and updating [this](https://github.com/layer5io/layer5/blob/master/src/collections/landscape/smi.js) json object
3. Using the GitHub API for creating a pull request at https://github.com/layer5io/layer5

For 1, the best would be to have a new `view` command for `mesheryctl mesh validate` abiding by mesheryctl SMI conformance [spec](https://docs.google.com/document/d/1E0u9twIcHrnEa0NgytNxobQVRh6EnujfQU5Y0Ocvdq8/edit#)

For 3, I'm unsure about how frequently will they be triggering this. // @leecalcote 
* Assuming that service mesh projects will be running this action when they make a new release. Creating a PR on every run is sane.
* If they integrate this in a workflow which gets triggered too frequently, we'll need to provide a configuration option on to publish-results or not.

**Comment by leecalcote** [comment]
When Meshery Cloud is used as the provider smi conformance results are persisted and can be publicly retrieved at https://meshery.layer5.io/smi/results/public

**Comment by leecalcote** [comment]
Here is an example of its use - https://github.com/meshery/meshery.io/blob/master/collections/_pages/smi.html

**Comment by s1ntaxe770r** [comment]
@leecalcote does this mean when we obtain conformance results all we need to do is make a POST request to https://meshery.layer5.io/smi/results/public with the data from that run?

**Comment by leecalcote** [comment]
@s1ntaxe770r I didn't see this previously. Results are funneled through the Provider.

**Comment by DelusionalOptimist** [comment]
Since we're able to use the cloud provider and also persist the results in it, I guess this requirement  has been satisfied. Please reopen if misinterpreted. // @leecalcote @s1ntaxe770r
