### ISSUE TITLE
only deploy the specified service mesh's adapter

### ISSUE THREAD

**Issue by DelusionalOptimist** [layer5io/meshery-smi-conformance-action#33]
Reported by @navendu-pottekkat in https://github.com/layer5io/meshery-smi-conformance-action/pull/32

**Current behavior**
Currently, the action deploys all the adapters regardless of the service mesh being used because the `$service_mesh_adapter` is not being read correctly in https://github.com/layer5io/meshery-smi-conformance-action/blob/4a1f84c15dae29250caf33ecc96233a3d856562e/meshery.sh#L40 

**Desired behavior**
Only the desired adapter should be added to `~/.meshery/config.yaml` while creating the new context so as to deploy only that adapter and prevent bloat.

**Further description**
There is an error being thrown when the context is being created which I believe is causing the default config file being created.

![Screenshot 2021-08-14 at 2 29 23 AM](https://user-images.githubusercontent.com/49474499/129418687-e8ef37ac-00b4-4571-b848-2532d3accf91.png)

The issue is with this one line:

```
mesheryctl system context create new-context --adapters $service_mesh_adapter --platform docker --url http://localhost:9081 --set --yes
```
And I believe that it may have to do something with passing the `service_mesh_adapter` variable.

Maybe changing it to `--adapters="$service_mesh_adapter"` or something like that to make sure that we are not passing any extra arguments there would help.

This line runs fine locally when run as shown below. So the issue I mentioned above may causing this.

![Screenshot 2021-08-14 at 2 36 26 AM](https://user-images.githubusercontent.com/49474499/129418532-edfe5ef1-c543-4e22-bb18-51a9e827ddf1.png)

**Comment by leecalcote** [comment]
What value were you passing in `$service_mesh_adapter`?

**Comment by DelusionalOptimist** [comment]
> What value were you passing in $service_mesh_adapter?

@leecalcote `meshery-service_mesh_name`. In accordance with https://github.com/meshery/meshery/blob/master/docker-compose.yaml#L16-L63
(service mesh name here is not SMP protos friendly)
