### ISSUE TITLE
Create SMI Conformance badge

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery-smi-conformance-action#36]
#### Current Behavior

Users are able to run SMI Conformance test and view the percentage of the tests passed in Meshery.

#### Desired Behavior

Create a badge that can be used in the README to show the pass percentage of the SMI Conformance test that was most recently done. Something similar to this: ![SMI Conformance Badge](https://img.shields.io/badge/SMI%20Conformance-50%25-orange)

#### Implementation

This might require more changes around the action but here is what I'm proposing:

1. Use the [custom endpoints feature](https://shields.io/endpoint) from [Shields IO](https://shields.io/) to generate the dynamic badge.
2. Create a JSON endpoint in [meshery.io/service-mesh-interface](https://meshery.io/service-mesh-interface) to fetch the details to create the dynamic badge. This assumes that each of the participating service mesh has an official account that updates this data as they make new releases.

#### Blockers
1. No official accounts for service mesh projects.
2. Schedule of reporting: How quickly are the changes in test results reflected on the SMI Conformance Dashboard?

**This issue might require more thought so this is just a draft proposal.**

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by RajGM** [comment]
Hi @navendu-pottekkat 
I would like to start contributing through this one.

**Comment by soumya-dash3** [comment]
Hello, I'm an contributor at open-force, can this issue be assigned to me? @Nikhil-Ladha  @navendu-pottekkat

**Comment by soumya-dash3** [comment]
Hello, I'm a contributor at Open-Force. Can this issue be assigned to me? @Nikhil-Ladha @navendu-pottekkat @leecalcote

**Comment by leecalcote** [comment]
Closing out as undesired.

What would be helpful instead is the addition of test version # on the results dashboards on [meshery.io/smi](http://meshery.io/smi) and [layer5.io/landscape#smi](http://layer5.io/landscape#smi). The test that is run is versioned, but the results that are shown on the dashboards don’t allow users to navigate between result sets by test version #.
