### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/meshery-smi-conformance-action#46]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Sankhadip-Roy** [comment]
I want to work on this .
But the link in the implementation is of Meshery UI. Shouldn't we have to use the link of the Layer5 designs.

**Comment by thisiskaransgit** [comment]
@Sankhadip-Roy, thank you for pointing this out, I've updated the description, go ahead with its one 🚀

**Comment by Sankhadip-Roy** [comment]
Contributor Resources is only present in the documentation.md file, not present in other issue templates.
& no template has a reference to Figma previously.
Do i have to add the link in documentation.md only? @thisiskaransgit

**Comment by thisiskaransgit** [comment]
@Sankhadip-Roy, update the all existing issue-templates with the contributing resources mentioned in Layer5.io's [issue_templates](https://github.com/layer5io/layer5/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#contributor-resources-and-handbook)

**Comment by Sankhadip-Roy** [comment]
Hello @thisiskaransgit , I submitted PR #47 to this issue. Could you please review it and provide feedback? Thank you! 😊
